import { Dashboard } from '@/components';
import { NextApiRequest } from 'next';
import Head from 'next/head';
import * as cookie from 'cookie';

export default function DashboardPage({ req }: { req: any }) {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Dashboard />
      </main>
    </>
  );
}

export async function getServerSideProps(context: {
  req: NextApiRequest;
  res: any;
}) {
  const { req } = context;

  const token = req.cookies;

  console.log('token ______________________________________', token);

  // if (!token) {
  //   return {
  //     redirect: {
  //       destination: '/login',
  //       permanent: false,
  //     },
  //   };
  // }

  return {
    props: {
      req: '',
    },
  };
}
