import Head from 'next/head'
import { Landing } from '@/components';


export default function Home() {
  return (
    <>
      <Head>
        <title>Collars Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Route: /</h1>
        <Landing />
      </main>
    </>
  );
}
