import Head from 'next/head';
import { Landing } from '@/components';
import { client } from '@/client';
import { gql } from '@apollo/client';

export default function Home({ breeds }: { breeds: any[] }) {
  console.log('breeds', breeds)
  return (
    <>
      <Head>
        <title>Collars Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Landing />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query GetBreeds {
        getBreeds {
          id
          breed
          species
        }
      }
    `,
  });

  return {
    props: {
      breeds: data.getBreeds,
    },
  };
}
